# prettier-ignore
name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Check out source code 
      - name: Login to custom Container Registry # Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker images # Build docker image
        uses: docker/build-push-action@v4.0.0
        with:
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/mother-mouse-discord:latest
      - name: Trigger Watchtower # Trigger Watchtower to update the running container
        run: 'curl -H "Authorization: Bearer ${{ secrets.WATCHTOWER_TOKEN }}" ${{  secrets.WATCHTOWER_URL }} -s'